### ISSUE TITLE
Error loading Python lib

### ISSUE THREAD

**Issue by JARVIS-AI** [vfosterm/NordVPN-NetworkManager-Gui#16]
Hi
Thank you for this tool

I have an issue I can't run launch Node

**Related Info**
OS : Elementary OS (Ubuntu Based)
OS State : Updated - Working smoothly
Installed Python
Installed GCC
Installed Clang
Installed All network-manager dependencies before installing this tool
Reconfigured Desktop entry by myself not used install sh

**Exact error output** :

```sh
[14684] Error loading Python lib '/home/jarvis/.jarvis_apps/apps/NordVPN/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/jarvis/.jarvis_apps/apps/NordVPN/libpython3.7m.so.1.0)
```

**Notes** :

I think I should compile this tool in my OS again by myself to reversion GLIBC same as mine.

Also I have the library file ``libm.so.6`` in that directory ``/lib/x86_64-linux-gnu`` but as I think the GLIBC is not right for this tool so this tool doesn't accept it. 

What do you think ?

**Comment by vfosterm** [comment]
Yes absolutely! I used to make compatibility builds but it was getting a
bit time consuming. I guess I should try to automate that somehow.
The reason for the error is that you are using an older version of glibc.
If you like I will compile you a compatible version when I get home
tonight.

**Comment by JARVIS-AI** [comment]
Also I tested this with toolchain ppa in ubuntu - But not work
Can you make this automate with glibc 
I will study and pull request if you can't
Till then can you make compatible version

**Comment by JARVIS-AI** [comment]
My 
```sh
$: ldd --version
```

```sh
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

But your tool need **2.29** GLIBC

**Comment by MarkChr65** [comment]
If have absolutely the same issue - same OS and same GLIBC Version. I'm not so familiar to compile my own version, so is there anny chance to get a compiled version with 2.27 GLIBC?

Thanks in advance

Mark

**Comment by sawaYch** [comment]
> My
> 
> ```shell
> $: ldd --version
> ```
> 
> ```shell
> ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> ```
> 
> But your tool need **2.29** GLIBC

Same issue on KDE Neon (Ubuntu 18.04).
I think most of us don't really need a standalone executable (at least for me).
It works fine on my machine by just execute the program with py3.

**Comment by vfosterm** [comment]
Yes, compiling on Arch seems to have been a bad idea in this case :)
I will provide a compatibility build in the future and also make some instructions for running the script based version as @sawaYch suggests.

**Comment by SiL3NC3** [comment]
Still problem of missing GLIBC 2.29... when running on fresh MX Linux install.
Version 2.28 is available...
When could this be fixed?

**Comment by vfosterm** [comment]
Hi SiL3NC3, appologies for not maintaining this. I have in the meantime switched VPN providers and don't use this program myself. 
I will try to make time this weekend in order to get rid of the installation script and instead package and publish the application on pip.

**Comment by vfosterm** [comment]
Hi everyone, I have updated the application (fixed login authentication) and provided a new compatibility build.
Please let me know if this works for you while I investigate better options.

**Comment by mammo0** [comment]
Hello @vfosterm,

can you share, how you exactly build the application? The normal and the compatibility build?
Because I tried it with Pyinstaller and it worked on my local machine, but on any other PC it either fails with the Glibc problem like above or due to incompatibilities with GDK...

Thank you

**Comment by vfosterm** [comment]
Hi @mammo0,
I am building the application using pyinstaller.
The normal version is compiled on an up to date arch machine while the compatibility build is built on a older debian machine.
I will update this comment with the specifics.

**Comment by mammo0** [comment]
> The normal version is compiled on an up to date arch machine ...

Ok, this is why it worked out of the box for me, because I'm also using Arch.

I tried to use staticx for building a static linked binary, but also had some problems with that. For this problem I opened an issue on the staticx project: https://github.com/JonathonReinhart/staticx/issues/159

But as far as I understand the problem is not so easy to solve.

**Comment by patvdleer** [comment]
FYI; on Ubuntu 20.20 

```
[510608] Error loading Python lib '/home/patrick/Downloads/nord_vpn_v1-4-2/NordVPN/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/patrick/Downloads/nord_vpn_v1-4-2/NordVPN/libpython3.8.so.1.0)
```

**Comment by vfosterm** [comment]
If you are not on arch Linux or some other distro with an up to date kernel
please use the compatibility build.
