### ISSUE TITLE
install script would not work in Raspbian

### ISSUE THREAD

**Issue by goL-prog** [vfosterm/NordVPN-NetworkManager-Gui#19]
Tried to install the executable of _NordVPN Network Manager GUI_ in the latest Raspbian (on Ras Pi 3b+) by running **./install.sh** as per readme but failed.
I get this below:

**pi@raspberrypi:/usr/lib/NordVPN-GUI $ sudo ./install.sh
./install.sh: line 5: nmcli: command not found
./install.sh: line 5: [: =: unary operator expected
Saving desktop shortcut in /usr/share/applications**

When clicking on desktop shortcut, I get a sand-clock icon but no further.

I examined the script file and installed the networkmanager-openvpn dependency but still was unable to run this application

**Comment by vfosterm** [comment]
The release version was compiled on x86 so there is essentially no way that it will work.
The only option for you would be to execute the python script directly. This should not be too difficult but you would need python 3.8 and the required dependencies (pip install all of the imports at the top of the script).
I plan to move away from the precompiled binaries, so I hope to have a more compatible installer in the future.
