### ISSUE TITLE
My Name is Forest, Forest Gump.... A lil help guys / gals

### ISSUE THREAD

**Issue by GuardsRed928** [vfosterm/NordVPN-NetworkManager-Gui#31]
I searched for the step by step installation help and didn't have much luck. Sorry if this is a rather simpleton issue.

Ubuntu 20.04 LTS

I installed the nordvpn debian file after downloading off their web site. Logged in on the web as instructed from the command line succesfully and am running nordvpn a-ok from the command line. Changed a few settings to include auto-connect etc.

As for this Gui I are a little confused. Do I Install this main page (322kb) first before installing v1.4.2? And when installing v1.4.2 do I install the main first, or the compatibility version? Again, sorry...

https://github.com/vfosterm/NordVPN-NetworkManager-Gui/

In any event, I copied the v1.4.2 NordVpn directory into the NordVPN-NetworkManager-Gui-master directory. I made the script change for my Ubuntu per the previous post and have a Nord Vpn Icon happily sitting in my activity tray with all the rest, but when I click on it, it doesn't load.

Lost in a cornfield in Iowa. Thanks fer yer help.

P

**Comment by vfosterm** [comment]
Hi, NordVPN-NetworkManager uses the native systemd network manager and does not rely on any proprietary binaries provided by NordVPN. As for main version vs compatibility version this you will need to test though it seems for debian based systems the compatibility version is needed, only the download from the release section is required, you do not need to clone the repository.

Steps should be as follows:

1. Extract the release archive found in the release section to where you would like to install the program
2. Run the installation script
3. Execute the program using the desktop file
4. Avoid being abducted by aliens while in the cornfield

If there are issues try running the binary file directly from the terminal to get a more detailed error output.
