### ISSUE TITLE
Using install.sh, the desktop file points to nonexisting executable

### ISSUE THREAD

**Issue by logix2** [vfosterm/NordVPN-NetworkManager-Gui#8]
Using the install.sh script, a .desktop file is created that uses this path for the Exec: ```"$current_dir"/nord_vpn/launch_nord```. This file does not exist in the NordVPN-NetworkManager-Gui repository, and should point to ```nord_nm_gui.py``` instead.

**Comment by vfosterm** [comment]
The installation script is only intended for the release version. Which is simply a pyinstaller compiled version of nord_nm_gui.py. If you have all the requirements installed you can just launch the python script.

**Comment by vfosterm** [comment]
side note, I discovered an ipv6 ip leak today and added more aggressive ipv6 blocking. You should upgrade ASAP as Nord doesn't support IPV6 and your original IP will be exposed. I will be adding automated anonymity and connection testing to prevent this sort of thing in the future.
